package lyc.compiler;

import java_cup.runtime.*;
import lyc.compiler.main.Utility;
import lyc.compiler.main.SymbolTable;
import lyc.compiler.main.PolishArray;
import java.util.Stack;

class Parser;

action code {:
                Utility ut = Utility.getInstance();
                SymbolTable st = SymbolTable.getSymbolTable();
                PolishArray pa = PolishArray.getInstance();
            :}

// Terminals
terminal ASSIG;
terminal PLUS;
terminal SUB;
terminal MULT;
terminal DIV;
terminal OPEN_BRACKET;
terminal CLOSE_BRACKET;
terminal INTEGER_CONSTANT;
terminal IDENTIFIER;
terminal LE, GE, G, L, EQ, NEQ;
terminal INT, STRING, FLOAT;
terminal CTE_S;
terminal CURLY_BRACKET_OPN, CURLY_BRACKET_CLSD;
terminal SEMICOLON, COLON, COMA;
terminal STATIC;
terminal SQUARE_BRACKET_OPN, SQUARE_BRACKET_CLSD;
terminal VOID, MAIN, PUBLIC, CLASS, INIT, IF, ELSE;
terminal AND, OR, NOT;
terminal WRITE, READ, WHILE;
terminal FLOAT_CONSTANT;
terminal NEGATIVE_CONSTANT;
terminal IS_ZERO;
terminal EQUAL_EXPR;

// Non Terminals
non terminal sentence;
non terminal assignment;
non terminal valid_expression;
non terminal expression;
non terminal term;
non terminal factor;
non terminal program;
non terminal algo;
non terminal block_ini , block_pgrm, bloque_var;
non terminal var_decl, var_decl_2;
non terminal block_variables, tipo, variables, variable, asignacion, bloque_if, condicion, op_comp, bloque_while;
non terminal if_decl, else_decl, write_sent, read_sent;
non terminal sentencias_pgrm , sentencia_pgrm, sentencias_var, sentencia_var;
non terminal functionZ , functionE, function, l_exp;

// Start Symbol Definition
start with program;

/*
program ::= PUBLIC CLASS IDENTIFIER CURLY_BRACKET_OPN algo CURLY_BRACKET_CLSD {: System.out.println("Declaracion de Clase"); :};

algo ::= PUBLIC STATIC VOID MAIN OPEN_BRACKET STRING SQUARE_BRACKET_OPN SQUARE_BRACKET_CLSD IDENTIFIER CLOSE_BRACKET CURLY_BRACKET_OPN blocks CURLY_BRACKET_CLSD
         {: System.out.println("Declaracion de main"); :};
*/

program ::= block_ini block_pgrm {: System.out.println("Inicio de Programa -> bloque inicial + bloques");
                                    pa.exportToFile();
                                 :}
        |   block_ini {: System.out.println("Inicio de Programa -> bloque inicial sin programa"); :};

block_ini ::= bloque_var {: System.out.println("Bloque inicio -> Bloque variables"); :};

block_pgrm ::= sentencias_pgrm {: System.out.println("Bloque de Programa -> Sentencia de Programa"); :};

sentencias_pgrm ::= sentencias_pgrm sentencia_pgrm {: System.out.println("Sentencias Multiples de Programa"); :}
                |   sentencia_pgrm {: System.out.println("Sentencia Simple de Programa"); :};

sentencia_pgrm ::= asignacion | bloque_if | read_sent | write_sent | bloque_while {: System.out.println("Bloque/Sentencia Singular de Codigo"); :};

bloque_var ::= INIT CURLY_BRACKET_OPN sentencias_var CURLY_BRACKET_CLSD {: System.out.println("Bloque de Declaracion de Variables"); :};

sentencias_var ::= sentencias_var sentencia_var {: System.out.println("Sentencias de Declaracion Multiples de Variables"); :}
                |  sentencia_var {: System.out.println("Sentencia de Declaracion Simple de Variable"); :};

sentencia_var ::= variables COLON tipo {:
                                            System.out.println("Sentencia de Variable");
                                            String tipoDato = ut.desapilarType();
                                            Stack<String> stack = ut.getIdStack();
                                            Stack<String> auxStack = ut.getAuxStack();
                                            String type = ut.desapilarAux();

                                            while(!stack.isEmpty()) {
                                                st.addType(stack.pop(), tipoDato);
                                            }

                                            while(!auxStack.isEmpty()) {
                                                pa.insertar(type);
                                                pa.insertar(auxStack.pop());
                                                pa.insertar(":");
                                            }
                                       :};

variables ::= variables COMA variable {: System.out.println("Multiple Declaracion de Variables"); :}
            | variable {: System.out.println("Declaracion de Variable Simple"); :};

variable ::= IDENTIFIER:id {:
                                // Aca antes de apilar el "id" para luego asignarle su tipo, tengo que revisar que no este previamente en la tabla de simbolos
                                st.checkDuplicatedVariable("" + id);
                                System.out.println("Nombre de Variable");
                                ut.apilarId("" + id);
                                ut.apilarAux("" + id);
                           :};

tipo ::= INT {:
                System.out.println("Tipo de Variable/s 'Int'");
                ut.apilarType("Int");
                ut.apilarAux("Int");
             :}
       | FLOAT {:
                    System.out.println("Tipo de Variable/s 'Float'");
                    ut.apilarType("Float");
                    ut.apilarAux("Float");
               :}
       | STRING {:
                    System.out.println("Tipo de Variable/s 'String'");
                    ut.apilarType("String");
                    ut.apilarAux("String");
                :};

asignacion ::= sentence {: System.out.println("Asignacion Numerica (Sentencia)"); :}
             | IDENTIFIER:id ASSIG CTE_S:string {: System.out.println("Asignacion de String");
                                            st.checkUndeclaredVariable("" + id);
                                            st.checkStringAssig("" + id);

                                            pa.insertar("" + string);
                                            pa.insertar("" + id);
                                            pa.insertar("=");

                                         :};

bloque_if ::= if_decl {: System.out.println("Bloque If sin Else"); :}
            | if_decl else_decl {: System.out.println("Bloque If con Else"); :};

if_decl ::= IF OPEN_BRACKET condicion CLOSE_BRACKET CURLY_BRACKET_OPN sentencias_pgrm CURLY_BRACKET_CLSD {: System.out.println("Declaracion de Bloque IF"); :};

else_decl ::= ELSE CURLY_BRACKET_OPN sentencias_pgrm CURLY_BRACKET_CLSD {: System.out.println("Bloque Else de If"); :};

condicion ::= expression op_comp expression {: System.out.println("Condicion de IF simple");
                                               ut.checkConditionType();
                                            :}
            | NOT expression op_comp expression {: System.out.println("Condicion de IF 'NOT' simple");
                                                   ut.checkConditionType();
                                                :}

            | expression op_comp expression AND expression op_comp expression {: System.out.println("Condicion de IF multiple 'AND'");
                                                                                 ut.checkConditionType();
                                                                              :}
            | NOT expression op_comp expression AND expression op_comp expression {: System.out.println("Condicion de IF multiple 'AND' y 'NOT' al inicio");
                                                                                     ut.checkConditionType();
                                                                                  :}
            | expression op_comp expression AND NOT expression op_comp expression {: System.out.println("Condicion de IF multiple 'AND' y 'NOT' al final");
                                                                                     ut.checkConditionType();
                                                                                  :}
            | NOT expression op_comp expression AND NOT expression op_comp expression {: System.out.println("Condicion de IF multiple 'AND' y 'NOT' en ambas condiciones");
                                                                                         ut.checkConditionType();
                                                                                      :}

            | expression op_comp expression OR expression op_comp expression {: System.out.println("Condicion de IF multiple 'OR'");
                                                                                ut.checkConditionType();
                                                                             :}
            | NOT expression op_comp expression OR expression op_comp expression {: System.out.println("Condicion de IF multiple 'OR' y 'NOT' al inicio");
                                                                                    ut.checkConditionType();
                                                                                 :}
            | expression op_comp expression OR NOT expression op_comp expression {: System.out.println("Condicion de IF multiple 'OR' y 'NOT' al final");
                                                                                    ut.checkConditionType();
                                                                                 :}
            | NOT expression op_comp expression OR NOT expression op_comp expression {: System.out.println("Condicion de IF multiple 'OR' y 'NOT' en ambas condiciones");
                                                                                        ut.checkConditionType();
                                                                                     :}

            | function {: System.out.println("Funcion como comparacion"); :};

op_comp ::= GE {: System.out.println("Operador >="); :}
            | LE {: System.out.println("Operador <="); :}
            | G {: System.out.println("Operador >"); :}
            | L {: System.out.println("Operador <"); :}
            | EQ {: System.out.println("Operador =="); :}
            | NEQ {: System.out.println("Operador !="); :};

write_sent ::= WRITE OPEN_BRACKET CTE_S CLOSE_BRACKET {: System.out.println("Write con STRING literal"); :}
             | WRITE OPEN_BRACKET IDENTIFIER:id {: st.checkUndeclaredVariable("" + id); :} CLOSE_BRACKET {: System.out.println("Write con variable"); :};

read_sent ::= READ OPEN_BRACKET IDENTIFIER:id {: st.checkUndeclaredVariable("" + id); :} CLOSE_BRACKET {: System.out.println("Lectura de una variable"); :};

bloque_while ::= WHILE OPEN_BRACKET condicion CLOSE_BRACKET CURLY_BRACKET_OPN sentencias_pgrm CURLY_BRACKET_CLSD {: System.out.println("Bloque While"); :};

sentence ::= assignment {: System.out.println("End"); :};
assignment ::= IDENTIFIER:id ASSIG expression {:
                                                 System.out.println("Assignment");
                                                 st.checkUndeclaredVariable("" + id);

                                                 if(ut.notEmptyTypeStacks()) {
                                                    throw new RuntimeException("La expresion arimetica contiene operandos de diferente tipo.");
                                                 }

                                                 ut.checkExpressionAssig(st.getDataType("" + id), "" + id);

                                                 ut.vaciarIntType();
                                                 ut.vaciarFloatType();

                                                 pa.insertar("" + id);
                                                 pa.insertar("=");

                                              :};

valid_expression ::= expression {:
                                    if(ut.notEmptyTypeStacks()) {
                                        throw new RuntimeException("La expresion arimetica contiene operandos de diferente tipo.");
                                    }

                                    ut.vaciarIntType();
                                    ut.vaciarFloatType();

                                :};

expression ::= expression PLUS term {: System.out.println("+");
                                       pa.insertar("+");
                                    :};
expression ::= expression SUB term {: System.out.println("-");
                                      pa.insertar("-");
                                   :};
expression ::= term {: System.out.println("Expression = Term"); :};
term ::= term MULT factor {: System.out.println("*");
                             pa.insertar("*");
                          :};
term ::= term DIV factor {: System.out.println("/");
                            pa.insertar("/");
                         :};
term ::= factor {: System.out.println("Term = factor"); :};

factor ::= IDENTIFIER:id  {: System.out.println("Id: " + id);

                             st.checkUndeclaredVariable("" + id);
                             ut.pushDataTypeId(st.getDataType("" + id), "" + id);
                             pa.insertar("" + id);

                          :};

factor ::= INTEGER_CONSTANT:constant {: System.out.println("Constant: " + constant );

                                        ut.apilarIntType("int");
                                        pa.insertar("" + constant);
                                     :};

factor ::= FLOAT_CONSTANT:constant {: System.out.println("Constant: " + constant);

                                      ut.apilarFloatType("float");
                                      pa.insertar("" + constant);
                                   :};

factor ::= SUB factor {: System.out.println("Regla de mi amigazo <3");
                      :}; // TODO: No olvidarse de cambiar el nombre | Revisar accion semantica

factor ::= OPEN_BRACKET expression CLOSE_BRACKET {: System.out.println("Factor = (Expression)"); :};

function ::= functionE {: System.out.println("Funtion equalExpressions() "); :}
           | functionZ {: System.out.println("Funcion isZero() "); :};

functionE ::= EQUAL_EXPR OPEN_BRACKET l_exp CLOSE_BRACKET {: System.out.println("Funcion equalExpressions"); :};

l_exp ::= l_exp COMA valid_expression {: System.out.println("Lista de Expresiones Multiples"); :}
      |   valid_expression {: System.out.println("Expresion Simple"); :};

functionZ ::= IS_ZERO OPEN_BRACKET valid_expression CLOSE_BRACKET {: System.out.println("isZero(Expression)"); :};
