
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package lyc.compiler;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int LLAV_ABRE = 29;
  public static final int OPA_NOT = 16;
  public static final int ELSE = 3;
  public static final int INT = 25;
  public static final int DECVAR = 5;
  public static final int WHILE = 6;
  public static final int OPA_MEN = 18;
  public static final int OPA_OR = 15;
  public static final int IF = 4;
  public static final int ID = 2;
  public static final int OPA_MAIG = 20;
  public static final int OP_SUMA = 10;
  public static final int PAR_ABRE = 31;
  public static final int LLAV_CIER = 30;
  public static final int BOOLEAN = 28;
  public static final int OPA_IGUAL = 19;
  public static final int COMA = 34;
  public static final int STRING = 27;
  public static final int FLOAT = 26;
  public static final int DOS_PTOS = 33;
  public static final int EOF = 0;
  public static final int CTE_S = 24;
  public static final int SALIDA = 8;
  public static final int OPA_MEIG = 21;
  public static final int OPA_MAY = 17;
  public static final int OP_DIV = 13;
  public static final int error = 1;
  public static final int ENTRADA = 7;
  public static final int OP_MULT = 12;
  public static final int CTE_F = 23;
  public static final int OP_RESTA = 11;
  public static final int CTE_E = 22;
  public static final int OPA_AND = 14;
  public static final int PAR_CIER = 32;
  public static final int ASIG = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ELSE",
  "IF",
  "DECVAR",
  "WHILE",
  "ENTRADA",
  "SALIDA",
  "ASIG",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULT",
  "OP_DIV",
  "OPA_AND",
  "OPA_OR",
  "OPA_NOT",
  "OPA_MAY",
  "OPA_MEN",
  "OPA_IGUAL",
  "OPA_MAIG",
  "OPA_MEIG",
  "CTE_E",
  "CTE_F",
  "CTE_S",
  "INT",
  "FLOAT",
  "STRING",
  "BOOLEAN",
  "LLAV_ABRE",
  "LLAV_CIER",
  "PAR_ABRE",
  "PAR_CIER",
  "DOS_PTOS",
  "COMA"
  };
}

